[package]
name = "silver-first-entry-alpha"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []

[dependencies]
bincode = "=1.3.3"
solana-program = "=1.18.26"
spl-token-2022 = { version = "=3.0.5", features = ["no-entrypoint"] }
spl-token-metadata-interface = "=0.3.5"
spl-transfer-hook-interface = "=0.6.5"
spl-tlv-account-resolution = "=0.6.5"
